---
version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /mnt:/mnt
      - /mnt/n0tDocker/n0tIndexer/Jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  nzbhydra2:
    image: linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt:/mnt
      - /mnt/n0tDocker/n0tIndexer/nzbHydra2:/config
    ports:
      - 5076:5076
    restart: unless-stopped
